version: '3'
services:
  mongo:
    restart: always
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - './volumes/mongo:/data/db'
  redis:
    restart: always
    image: bitnami/redis:latest
    volumes:
      - './volumes/data:/bitnami/redis/data'
    environment:
      - REDIS_PASSWORD=Password1Startup
  app:
    restart: always
    build:
      context: .
    command: nodemon --ignore './static/' server.js
    depends_on:
      - redis
      - mongo
    links:
      - redis
      - mongo
    ports:
      - '80:3000'
      - '3020:3020'
    volumes:
      - './:/app/'
      - './volumes:/app/volumes/'
      # - /app/node_modules/
