version: '3'
services:
  redis:
    restart: always
    image: bitnami/redis:latest
    ports:
      - '6380:6379'
    volumes:
      - './volumes/data:/bitnami/redis/data'
    environment:
      - REDIS_PASSWORD=Password1Startup
  app:
    restart: always
    build:
      context: .
    # command: nodemon --ignore './static/' server.js
    depends_on:
      - redis
    links:
      - redis
    ports:
      - '80:3000'
      - '3020:3020'
    volumes:
      - './:/app/'
      - './volumes:/app/volumes/'
      - /app/node_modules/
