version: '3'
services:
  mongo:
    restart: always
    image: mongo
    volumes:
      - './volumes/mongo:/data/db'
    ports:
      - 27017:27017
  redis:
    restart: always
    image: bitnami/redis:latest
    volumes:
      - 'mongo:/bitnami/redis/data'
    environment:
      - REDIS_PASSWORD=Password1Startup
  app:
    restart: always
    build:
      context: .
    command: nodemon --ignore './static/' server.js
    depends_on:
      - redis
      - mongo
    links:
      - redis
      - mongo
    ports:
      - '3000:3000'
      - '3020:3020'
    volumes:
      - './:/app/'
      - './volumes:/app/volumes/'
      # - /app/node_modules/
volumes:
  mongo: