version: '3'
services:
  mongo:
    restart: always
    image: mongo
    logging:
      driver: "none"
    volumes:
      - './volumes/mongo:/data/db'
  redis:
    restart: always
    image: bitnami/redis:latest
    volumes:
      - './volumes/redis:/bitnami/redis/data'
    environment:
      - REDIS_PASSWORD=Password1Startup
  api:
    restart: on-failure
    build:
      context: ./hodlapi.core
    command: bash -c "cd hodlapi.core && export NODE_ENV=production && node server.js"
    depends_on:
      - redis
      - mongo
    links:
      - redis
      - mongo
    ports:
      - '80:3000'
    volumes:
      - './:/app/'
      - '/app/node_modules'
  parser:
    restart: on-failure
    build:
      context: ./hodlapi.parser/
    command: bash -c "cd hodlapi.parser && export NODE_ENV=production && node server.js"
    depends_on:
      - redis
      - mongo
    links:
      - redis
      - mongo
    volumes:
      - './:/app/'
      - '/app/node_modules'
  filewriter:
    restart: on-failure
    build:
      context: ./hodlapi.fwriter/
    command: bash -c "cd hodlapi.fwriter && export NODE_ENV=production && node server.js"
    depends_on:
      - redis
      - mongo
    links:
      - redis
      - mongo
    ports:
      - '8080:8080'
    volumes:
      - './:/app/'
      - '/app/node_modules'
  seeds:
    restart: on-failure
    build:
      context: ./hodlapi.dbseeds/
    command: bash -c "cd hodlapi.dbseeds && export NODE_ENV=production && npx md-seed run"
    depends_on:
      - redis
      - mongo
    links:
      - redis
      - mongo
    volumes:
      - './:/app/'
      - '/app/node_modules'
  sockets:
    restart: always
    build:
      context: ./hodlapi.sockets/
    command: bash -c "cd hodlapi.sockets && export NODE_ENV=production && node server.js"
    depends_on:
      - redis
    links:
      - redis
    volumes:
      - './:/app/'
      - '/app/node_modules'
    ports:
      - '5000:5000'
  queue-dashboard:
    restart: always
    build:
      context: ./hodlapi.queue-dashboard/
    command: bash -c "cd hodlapi.queue-dashboard && export NODE_ENV=production && node server.js"
    depends_on:
      - redis
    links:
      - redis
    volumes:
      - './:/app/'
      - '/app/node_modules'
    ports:
      - '4567:4567'
volumes:
  mongo: