version: '3'
services:
  mongo:
    restart: always
    image: mongo
    logging:
      driver: "none"
    volumes:
      - './volumes/mongo:/data/db'
  redis:
    restart: always
    image: bitnami/redis:latest
    volumes:
      - './volumes/redis:/bitnami/redis/data'
    environment:
      - REDIS_PASSWORD=Password1Startup
  api:
    restart: on-failure
    build:
      context: ./hodlapi.core
    command: bash -c "cd hodlapi.core && export NODE_ENV=production && node server.js"
    depends_on:
      - redis
      - mongo
    links:
      - redis
      - mongo
    ports:
      - '80:3000'
    volumes:
      - './:/app/'
      - '/node_modules'
  parser:
    restart: on-failure
    build:
      context: ./hodlapi.parser/
    command: bash -c "cd hodlapi.parser && export NODE_ENV=production && node server.js"
    depends_on:
      - redis
      - mongo
    links:
      - redis
      - mongo
    volumes:
      - './:/app/'
      - './node_modules'
  filewriter:
    restart: on-failure
    build:
      context: ./hodlapi.fwriter/
    command: bash -c "cd hodlapi.fwriter && export NODE_ENV=production && node server.js"
    depends_on:
      - redis
      - mongo
    links:
      - redis
      - mongo
    volumes:
      - './:/app/'
      - 'node_modules'
  seeds:
    restart: on-failure
    build:
      context: ./hodlapi.dbseeds/
    command: bash -c "cd hodlapi.dbseeds && export NODE_ENV=production && node server.js"
    depends_on:
      - redis
      - mongo
    links:
      - redis
      - mongo
    volumes:
      - './:/app/'
      - '/node_modules'
volumes:
  mongo: